# Generated by Django 4.0.1 on 2022-02-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220112_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('product_bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought', to='products.product')),
                ('product_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered', to='products.offer')),
            ],
        ),
    ]
