# Generated by Django 4.0.1 on 2022-03-07 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product_bought',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought', to='products.product'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='product_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offered', to='products.offer'),
        ),
    ]
